name: Fetch AQI Data
on:
  schedule:
    - cron: "0 * * * *"  # Hourly
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or your preferred version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install hsfs==3.0.5
      
      - name: Run data fetch
        run: python src/features/fetch_data.py
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          ACCUWEATHER_API_KEY: ${{ secrets.ACCUWEATHER_API_KEY }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          TARGET_CITY: "karachi"  # or make this a secret if sensitive
      
      - name: Verify output
        run: |
          # Add simple verification like checking file timestamps
          ls -l src/features/
