name: AQI Training Pipeline (PKT)
on:
  schedule:
    - cron: "0 19 * * *"  # 00:00 PKT (7 PM UTC)
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Karachi

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt shap
          echo "$(date +'%Y-%m-%d %H:%M:%S %Z')" >> run.log

      - name: Process data
        run: |
          python -m src.process --lookback_days 90
          echo "Data processed at $(date +'%Y-%m-%d %H:%M:%S %Z')" >> timing.log
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          PYTHONUNBUFFERED: 1

      - name: Train model
        run: |
          python -m src.models.train
          echo "Training completed at $(date +'%Y-%m-%d %H:%M:%S %Z')" >> timing.log
        if: always()

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts-${{ github.run_id }}
          path: |
            src/models/*.pkl
            src/models/shap_*.png
            *.log
        if: success() || failure()

      - name: Slack notification
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          slack-message: 'Workflow ${{ github.workflow }} failed! (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>)'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
