name: AQI Training Pipeline (PKT)
on:
  schedule:
    - cron: "0 19 * * *"  # 00:00 PKT (7 PM UTC)
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Karachi
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt shap matplotlib
          
      - name: Create model directory
        run: mkdir -p src/models

      - name: Process data
        run: |
          python -m src.features.process --lookback_days 90
          echo "Data processed at $(date +'%Y-%m-%d %H:%M:%S %Z')" > timing.log
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

      - name: Train model
        run: |
          python -m src.models.train
          echo "Training completed at $(date +'%Y-%m-%d %H:%M:%S %Z')" >> timing.log
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}   

      - name: Verify artifacts
        run: |
          echo "Generated files:"
          ls -lh src/models/
          [ -f src/models/3day_forecaster.pkl ] || exit 1
          [ -f src/models/shap_24h.png ] || exit 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts-${{ github.run_id }}
          path: |
            src/models/3day_forecaster.pkl
            src/models/shap_*.png
            timing.log
