name: AQI Training Pipeline (PKT)
on:
  schedule:
    - cron: "0 19 * * *"  # 00:00 PKT (7 PM UTC)
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Asia/Karachi
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pycaret catboost xgboost lightgbm
          
      - name: Create model directory
        run: mkdir -p src/models

      - name: Process data
        run: |
          python -m src.process
          echo "Data processed at $(date +'%Y-%m-%d %H:%M:%S %Z')" > timing.log
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

      - name: Train models
        run: |
          python -m src.train
          echo "Training completed at $(date +'%Y-%m-%d %H:%M:%S %Z')" >> timing.log
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: training-artifacts
          path: |
            src/models/*.pkl
            timing.log
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
