name: AQI Training Pipeline (PKT)
on:
  schedule:
    - cron: "0 19 * * *"  # 00:00 PKT (7 PM UTC)
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Prevent hanging
    env:
      TZ: Asia/Karachi  # Set timezone for logs

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt shap
          echo "$(date +'%Y-%m-%d %H:%M:%S %Z')" >> run.log  # Log PKT time
      
      - name: Process data
        run: |
          python -m src.process --lookback_days 90
          echo "Data processed at $(date +'%Y-%m-%d %H:%M:%S %Z')" >> timing.log
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          PYTHONUNBUFFERED: 1  # Real-time logging

      - name: Train model
        run: |
          python -m src.models.train
          echo "Training completed at $(date +'%Y-%m-%d %H:%M:%S %Z')" >> timing.log
        if: always()  # Run even if previous step fails

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts-${{ github.run_id }}
          path: |
            src/models/*.pkl
            src/models/shap_*.png
            *.log  # Includes timing logs
        if: success() || failure()  # Upload even on failure

      - name: Notify on failure
        if: failure()
        uses: actions-ecosystem/action-slack-notify@v1
        with:
          status: ${{ job.status }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
